### ISSUE TITLE
.then() and whenComplete() not work

### ISSUE THREAD

**Issue by usescrt** [ixsans/text_to_speech#6]
<img width="1154" alt="Screen Shot 2021-11-23 at 15 04 40" src="https://user-images.githubusercontent.com/10948596/143022912-2b5c92cc-c5e9-4e5e-bf28-13d8e56e3e83.png">

`tts.speak("test").then((value) => print("-------"));`

`ts.speak("test").whenComplete(() => print("------"));`

not working please help

**Comment by abayomiAkanji** [comment]
Hi @usescrt do you mean the text isn't playing? Are you able to log the error?

**Comment by usescrt** [comment]
Hi @abayomiAkanji 
Play is fine.
But print codes not work.

**Comment by abayomiAkanji** [comment]
Apparently, you wanted to perform an operation when the speech is over, right?

**Comment by abayomiAkanji** [comment]
Hi @usescrt 
Apparently, you wanted to perform an operation when the speech is over, right?

**Comment by usescrt** [comment]
Hi @abayomiAkanji 

Right.

**Comment by abayomiAkanji** [comment]
@usescrt you might want to try this:

```
await ts.speak("test") // actual implementation
// Any code here (after the await) should be executed after the speech is over.
```

**Comment by usescrt** [comment]
@abayomiAkanji thanks

**Comment by tascienes** [comment]
> @usescrt you might want to try this:
> 
> ```
> await ts.speak("test") // actual implementation
> // Any code here (after the await) should be executed after the speech is over.
> ```

Have you tried this on ios? Did it work successfully?

**Comment by silasrm** [comment]
Hi,

I'm trying await and then(), but no one executing on MacOS.

@usescrt in your code, is ok?

Thks!

**Comment by iliosana** [comment]
Hi @silasrm

I am facing the same problem, did you get it to work?

Thanks!
